import {
  article_picture_1,
  article_picture_10,
  article_picture_11,
  article_picture_12,
  article_picture_13,
  article_picture_14,
  article_picture_15,
  article_picture_16,
  article_picture_17,
  article_picture_18,
  article_picture_19,
  article_picture_2,
  article_picture_20,
  article_picture_21,
  article_picture_22,
  article_picture_23,
  article_picture_24,
  article_picture_25,
  article_picture_3,
  article_picture_4,
  article_picture_5,
  article_picture_6,
  article_picture_7,
  article_picture_8,
  article_picture_9,
} from "@/assets";
import { item_content } from "./blog-item";

export const article_data = [
  {
    id: "1",
    name: "article 1 - Explore Insights and Discover More",
    article_picture: article_picture_1,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "2",
    name: "article 2",
    article_picture: article_picture_2,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "3",
    name: "article 3",
    article_picture: article_picture_3,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "4",
    name: "article 4",
    article_picture: article_picture_4,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },

  {
    id: "5",
    name: "article 5",
    article_picture: article_picture_5,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "6",
    name: "article 6",
    article_picture: article_picture_6,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "7",
    name: "article 7",
    article_picture: article_picture_7,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "8",
    name: "article 8",
    article_picture: article_picture_8,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "9",
    name: "article 9",
    article_picture: article_picture_9,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "10",
    name: "article 10",
    article_picture: article_picture_10,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "11",
    name: "article 11",
    article_picture: article_picture_11,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "12",
    name: "article 12",
    article_picture: article_picture_12,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "13",
    name: "article 13",
    article_picture: article_picture_13,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "14",
    name: "article 14",
    article_picture: article_picture_14,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "15",
    name: "article 15",
    article_picture: article_picture_15,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "16",
    name: "article 16",
    article_picture: article_picture_16,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "17",
    name: "article 17",
    article_picture: article_picture_17,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "18",
    name: "article 18",
    article_picture: article_picture_18,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "19",
    name: "article 19",
    article_picture: article_picture_19,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "20",
    name: "article 20",
    article_picture: article_picture_20,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "21",
    name: "article 21",
    article_picture: article_picture_21,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "22",
    name: "article 22",
    article_picture: article_picture_22,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "23",
    name: "article 23",
    article_picture: article_picture_23,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "24",
    name: "article 24",
    article_picture: article_picture_24,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
  {
    id: "25",
    name: "article 25",
    article_picture: article_picture_25,
    article_second_picture: article_picture_1,
    article_content: item_content,
  },
];
