/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CategoriesCategoriesImport } from './routes/categories/_categories'
import { Route as AuthAuthImport } from './routes/auth/_auth'
import { Route as CategoriesCategoriesIndexImport } from './routes/categories/_categories.index'
import { Route as AccountAccountIndexImport } from './routes/account/_account.index'
import { Route as CategoriesProductProductImport } from './routes/categories/product/_product'
import { Route as AuthAuthVerificationImport } from './routes/auth/_auth.verification'
import { Route as AuthAuthChangePasswordImport } from './routes/auth/_auth.change-password'

// Create Virtual Routes

const CategoriesImport = createFileRoute('/categories')()
const AuthImport = createFileRoute('/auth')()
const CategoriesProductImport = createFileRoute('/categories/product')()
const CategoriesCategoriesIdLazyImport = createFileRoute(
  '/categories/_categories/$id',
)()
const AuthAuthVerificationConfirmedLazyImport = createFileRoute(
  '/auth/_auth/verification-confirmed',
)()
const AuthAuthSignupLazyImport = createFileRoute('/auth/_auth/signup')()
const AuthAuthSigninLazyImport = createFileRoute('/auth/_auth/signin')()
const AuthAuthForgetPasswordLazyImport = createFileRoute(
  '/auth/_auth/forget-password',
)()
const CategoriesProductProductIdLazyImport = createFileRoute(
  '/categories/product/_product/$id',
)()

// Create/Update Routes

const CategoriesRoute = CategoriesImport.update({
  path: '/categories',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesProductRoute = CategoriesProductImport.update({
  path: '/product',
  getParentRoute: () => CategoriesRoute,
} as any)

const CategoriesCategoriesRoute = CategoriesCategoriesImport.update({
  id: '/_categories',
  getParentRoute: () => CategoriesRoute,
} as any)

const AuthAuthRoute = AuthAuthImport.update({
  id: '/_auth',
  getParentRoute: () => AuthRoute,
} as any)

const CategoriesCategoriesIndexRoute = CategoriesCategoriesIndexImport.update({
  path: '/',
  getParentRoute: () => CategoriesCategoriesRoute,
} as any)

const AccountAccountIndexRoute = AccountAccountIndexImport.update({
  path: '/account/',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesCategoriesIdLazyRoute = CategoriesCategoriesIdLazyImport.update(
  {
    path: '/$id',
    getParentRoute: () => CategoriesCategoriesRoute,
  } as any,
).lazy(() =>
  import('./routes/categories/_categories.$id.lazy').then((d) => d.Route),
)

const AuthAuthVerificationConfirmedLazyRoute =
  AuthAuthVerificationConfirmedLazyImport.update({
    path: '/verification-confirmed',
    getParentRoute: () => AuthAuthRoute,
  } as any).lazy(() =>
    import('./routes/auth/_auth.verification-confirmed.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthAuthSignupLazyRoute = AuthAuthSignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => AuthAuthRoute,
} as any).lazy(() =>
  import('./routes/auth/_auth.signup.lazy').then((d) => d.Route),
)

const AuthAuthSigninLazyRoute = AuthAuthSigninLazyImport.update({
  path: '/signin',
  getParentRoute: () => AuthAuthRoute,
} as any).lazy(() =>
  import('./routes/auth/_auth.signin.lazy').then((d) => d.Route),
)

const AuthAuthForgetPasswordLazyRoute = AuthAuthForgetPasswordLazyImport.update(
  {
    path: '/forget-password',
    getParentRoute: () => AuthAuthRoute,
  } as any,
).lazy(() =>
  import('./routes/auth/_auth.forget-password.lazy').then((d) => d.Route),
)

const CategoriesProductProductRoute = CategoriesProductProductImport.update({
  id: '/_product',
  getParentRoute: () => CategoriesProductRoute,
} as any)

const AuthAuthVerificationRoute = AuthAuthVerificationImport.update({
  path: '/verification',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthChangePasswordRoute = AuthAuthChangePasswordImport.update({
  path: '/change-password',
  getParentRoute: () => AuthAuthRoute,
} as any)

const CategoriesProductProductIdLazyRoute =
  CategoriesProductProductIdLazyImport.update({
    path: '/$id',
    getParentRoute: () => CategoriesProductProductRoute,
  } as any).lazy(() =>
    import('./routes/categories/product/_product.$id.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/_auth': {
      id: '/auth/_auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthImport
      parentRoute: typeof AuthRoute
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesImport
      parentRoute: typeof rootRoute
    }
    '/categories/_categories': {
      id: '/categories/_categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesCategoriesImport
      parentRoute: typeof CategoriesRoute
    }
    '/auth/_auth/change-password': {
      id: '/auth/_auth/change-password'
      path: '/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof AuthAuthChangePasswordImport
      parentRoute: typeof AuthAuthImport
    }
    '/auth/_auth/verification': {
      id: '/auth/_auth/verification'
      path: '/verification'
      fullPath: '/auth/verification'
      preLoaderRoute: typeof AuthAuthVerificationImport
      parentRoute: typeof AuthAuthImport
    }
    '/categories/product': {
      id: '/categories/product'
      path: '/product'
      fullPath: '/categories/product'
      preLoaderRoute: typeof CategoriesProductImport
      parentRoute: typeof CategoriesImport
    }
    '/categories/product/_product': {
      id: '/categories/product/_product'
      path: '/product'
      fullPath: '/categories/product'
      preLoaderRoute: typeof CategoriesProductProductImport
      parentRoute: typeof CategoriesProductRoute
    }
    '/auth/_auth/forget-password': {
      id: '/auth/_auth/forget-password'
      path: '/forget-password'
      fullPath: '/auth/forget-password'
      preLoaderRoute: typeof AuthAuthForgetPasswordLazyImport
      parentRoute: typeof AuthAuthImport
    }
    '/auth/_auth/signin': {
      id: '/auth/_auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthAuthSigninLazyImport
      parentRoute: typeof AuthAuthImport
    }
    '/auth/_auth/signup': {
      id: '/auth/_auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthAuthSignupLazyImport
      parentRoute: typeof AuthAuthImport
    }
    '/auth/_auth/verification-confirmed': {
      id: '/auth/_auth/verification-confirmed'
      path: '/verification-confirmed'
      fullPath: '/auth/verification-confirmed'
      preLoaderRoute: typeof AuthAuthVerificationConfirmedLazyImport
      parentRoute: typeof AuthAuthImport
    }
    '/categories/_categories/$id': {
      id: '/categories/_categories/$id'
      path: '/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof CategoriesCategoriesIdLazyImport
      parentRoute: typeof CategoriesCategoriesImport
    }
    '/account/_account/': {
      id: '/account/_account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountAccountIndexImport
      parentRoute: typeof rootRoute
    }
    '/categories/_categories/': {
      id: '/categories/_categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesCategoriesIndexImport
      parentRoute: typeof CategoriesCategoriesImport
    }
    '/categories/product/_product/$id': {
      id: '/categories/product/_product/$id'
      path: '/$id'
      fullPath: '/categories/product/$id'
      preLoaderRoute: typeof CategoriesProductProductIdLazyImport
      parentRoute: typeof CategoriesProductProductImport
    }
  }
}

// Create and export the route tree

interface AuthAuthRouteChildren {
  AuthAuthChangePasswordRoute: typeof AuthAuthChangePasswordRoute
  AuthAuthVerificationRoute: typeof AuthAuthVerificationRoute
  AuthAuthForgetPasswordLazyRoute: typeof AuthAuthForgetPasswordLazyRoute
  AuthAuthSigninLazyRoute: typeof AuthAuthSigninLazyRoute
  AuthAuthSignupLazyRoute: typeof AuthAuthSignupLazyRoute
  AuthAuthVerificationConfirmedLazyRoute: typeof AuthAuthVerificationConfirmedLazyRoute
}

const AuthAuthRouteChildren: AuthAuthRouteChildren = {
  AuthAuthChangePasswordRoute: AuthAuthChangePasswordRoute,
  AuthAuthVerificationRoute: AuthAuthVerificationRoute,
  AuthAuthForgetPasswordLazyRoute: AuthAuthForgetPasswordLazyRoute,
  AuthAuthSigninLazyRoute: AuthAuthSigninLazyRoute,
  AuthAuthSignupLazyRoute: AuthAuthSignupLazyRoute,
  AuthAuthVerificationConfirmedLazyRoute:
    AuthAuthVerificationConfirmedLazyRoute,
}

const AuthAuthRouteWithChildren = AuthAuthRoute._addFileChildren(
  AuthAuthRouteChildren,
)

interface AuthRouteChildren {
  AuthAuthRoute: typeof AuthAuthRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthRoute: AuthAuthRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CategoriesCategoriesRouteChildren {
  CategoriesCategoriesIdLazyRoute: typeof CategoriesCategoriesIdLazyRoute
  CategoriesCategoriesIndexRoute: typeof CategoriesCategoriesIndexRoute
}

const CategoriesCategoriesRouteChildren: CategoriesCategoriesRouteChildren = {
  CategoriesCategoriesIdLazyRoute: CategoriesCategoriesIdLazyRoute,
  CategoriesCategoriesIndexRoute: CategoriesCategoriesIndexRoute,
}

const CategoriesCategoriesRouteWithChildren =
  CategoriesCategoriesRoute._addFileChildren(CategoriesCategoriesRouteChildren)

interface CategoriesProductProductRouteChildren {
  CategoriesProductProductIdLazyRoute: typeof CategoriesProductProductIdLazyRoute
}

const CategoriesProductProductRouteChildren: CategoriesProductProductRouteChildren =
  {
    CategoriesProductProductIdLazyRoute: CategoriesProductProductIdLazyRoute,
  }

const CategoriesProductProductRouteWithChildren =
  CategoriesProductProductRoute._addFileChildren(
    CategoriesProductProductRouteChildren,
  )

interface CategoriesProductRouteChildren {
  CategoriesProductProductRoute: typeof CategoriesProductProductRouteWithChildren
}

const CategoriesProductRouteChildren: CategoriesProductRouteChildren = {
  CategoriesProductProductRoute: CategoriesProductProductRouteWithChildren,
}

const CategoriesProductRouteWithChildren =
  CategoriesProductRoute._addFileChildren(CategoriesProductRouteChildren)

interface CategoriesRouteChildren {
  CategoriesCategoriesRoute: typeof CategoriesCategoriesRouteWithChildren
  CategoriesProductRoute: typeof CategoriesProductRouteWithChildren
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesCategoriesRoute: CategoriesCategoriesRouteWithChildren,
  CategoriesProductRoute: CategoriesProductRouteWithChildren,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthRouteWithChildren
  '/categories': typeof CategoriesCategoriesRouteWithChildren
  '/auth/change-password': typeof AuthAuthChangePasswordRoute
  '/auth/verification': typeof AuthAuthVerificationRoute
  '/categories/product': typeof CategoriesProductProductRouteWithChildren
  '/auth/forget-password': typeof AuthAuthForgetPasswordLazyRoute
  '/auth/signin': typeof AuthAuthSigninLazyRoute
  '/auth/signup': typeof AuthAuthSignupLazyRoute
  '/auth/verification-confirmed': typeof AuthAuthVerificationConfirmedLazyRoute
  '/categories/$id': typeof CategoriesCategoriesIdLazyRoute
  '/account': typeof AccountAccountIndexRoute
  '/categories/': typeof CategoriesCategoriesIndexRoute
  '/categories/product/$id': typeof CategoriesProductProductIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthRouteWithChildren
  '/categories': typeof CategoriesCategoriesIndexRoute
  '/auth/change-password': typeof AuthAuthChangePasswordRoute
  '/auth/verification': typeof AuthAuthVerificationRoute
  '/categories/product': typeof CategoriesProductProductRouteWithChildren
  '/auth/forget-password': typeof AuthAuthForgetPasswordLazyRoute
  '/auth/signin': typeof AuthAuthSigninLazyRoute
  '/auth/signup': typeof AuthAuthSignupLazyRoute
  '/auth/verification-confirmed': typeof AuthAuthVerificationConfirmedLazyRoute
  '/categories/$id': typeof CategoriesCategoriesIdLazyRoute
  '/account': typeof AccountAccountIndexRoute
  '/categories/product/$id': typeof CategoriesProductProductIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/_auth': typeof AuthAuthRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/categories/_categories': typeof CategoriesCategoriesRouteWithChildren
  '/auth/_auth/change-password': typeof AuthAuthChangePasswordRoute
  '/auth/_auth/verification': typeof AuthAuthVerificationRoute
  '/categories/product': typeof CategoriesProductRouteWithChildren
  '/categories/product/_product': typeof CategoriesProductProductRouteWithChildren
  '/auth/_auth/forget-password': typeof AuthAuthForgetPasswordLazyRoute
  '/auth/_auth/signin': typeof AuthAuthSigninLazyRoute
  '/auth/_auth/signup': typeof AuthAuthSignupLazyRoute
  '/auth/_auth/verification-confirmed': typeof AuthAuthVerificationConfirmedLazyRoute
  '/categories/_categories/$id': typeof CategoriesCategoriesIdLazyRoute
  '/account/_account/': typeof AccountAccountIndexRoute
  '/categories/_categories/': typeof CategoriesCategoriesIndexRoute
  '/categories/product/_product/$id': typeof CategoriesProductProductIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/categories'
    | '/auth/change-password'
    | '/auth/verification'
    | '/categories/product'
    | '/auth/forget-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/verification-confirmed'
    | '/categories/$id'
    | '/account'
    | '/categories/'
    | '/categories/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/categories'
    | '/auth/change-password'
    | '/auth/verification'
    | '/categories/product'
    | '/auth/forget-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/verification-confirmed'
    | '/categories/$id'
    | '/account'
    | '/categories/product/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/auth/_auth'
    | '/categories'
    | '/categories/_categories'
    | '/auth/_auth/change-password'
    | '/auth/_auth/verification'
    | '/categories/product'
    | '/categories/product/_product'
    | '/auth/_auth/forget-password'
    | '/auth/_auth/signin'
    | '/auth/_auth/signup'
    | '/auth/_auth/verification-confirmed'
    | '/categories/_categories/$id'
    | '/account/_account/'
    | '/categories/_categories/'
    | '/categories/product/_product/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  CategoriesRoute: typeof CategoriesRouteWithChildren
  AccountAccountIndexRoute: typeof AccountAccountIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  CategoriesRoute: CategoriesRouteWithChildren,
  AccountAccountIndexRoute: AccountAccountIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/categories",
        "/account/_account/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth",
      "children": [
        "/auth/_auth"
      ]
    },
    "/auth/_auth": {
      "filePath": "auth/_auth.tsx",
      "parent": "/auth",
      "children": [
        "/auth/_auth/change-password",
        "/auth/_auth/verification",
        "/auth/_auth/forget-password",
        "/auth/_auth/signin",
        "/auth/_auth/signup",
        "/auth/_auth/verification-confirmed"
      ]
    },
    "/categories": {
      "filePath": "categories",
      "children": [
        "/categories/_categories",
        "/categories/product"
      ]
    },
    "/categories/_categories": {
      "filePath": "categories/_categories.tsx",
      "parent": "/categories",
      "children": [
        "/categories/_categories/$id",
        "/categories/_categories/"
      ]
    },
    "/auth/_auth/change-password": {
      "filePath": "auth/_auth.change-password.tsx",
      "parent": "/auth/_auth"
    },
    "/auth/_auth/verification": {
      "filePath": "auth/_auth.verification.tsx",
      "parent": "/auth/_auth"
    },
    "/categories/product": {
      "filePath": "categories/product",
      "parent": "/categories",
      "children": [
        "/categories/product/_product"
      ]
    },
    "/categories/product/_product": {
      "filePath": "categories/product/_product.tsx",
      "parent": "/categories/product",
      "children": [
        "/categories/product/_product/$id"
      ]
    },
    "/auth/_auth/forget-password": {
      "filePath": "auth/_auth.forget-password.lazy.tsx",
      "parent": "/auth/_auth"
    },
    "/auth/_auth/signin": {
      "filePath": "auth/_auth.signin.lazy.tsx",
      "parent": "/auth/_auth"
    },
    "/auth/_auth/signup": {
      "filePath": "auth/_auth.signup.lazy.tsx",
      "parent": "/auth/_auth"
    },
    "/auth/_auth/verification-confirmed": {
      "filePath": "auth/_auth.verification-confirmed.lazy.tsx",
      "parent": "/auth/_auth"
    },
    "/categories/_categories/$id": {
      "filePath": "categories/_categories.$id.lazy.tsx",
      "parent": "/categories/_categories"
    },
    "/account/_account/": {
      "filePath": "account/_account.index.tsx"
    },
    "/categories/_categories/": {
      "filePath": "categories/_categories.index.tsx",
      "parent": "/categories/_categories"
    },
    "/categories/product/_product/$id": {
      "filePath": "categories/product/_product.$id.lazy.tsx",
      "parent": "/categories/product/_product"
    }
  }
}
ROUTE_MANIFEST_END */
