/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CategoriesCategoriesImport } from './routes/categories/_categories'
import { Route as AuthAuthImport } from './routes/auth/_auth'
import { Route as AccountAccountImport } from './routes/account/_account'
import { Route as CategoriesCategoriesIndexImport } from './routes/categories/_categories.index'
import { Route as AccountAccountIndexImport } from './routes/account/_account.index'
import { Route as AuthAuthVerificationConfirmedImport } from './routes/auth/_auth.verification-confirmed'
import { Route as AuthAuthVerificationImport } from './routes/auth/_auth.verification'
import { Route as AuthAuthSigninImport } from './routes/auth/_auth.signin'
import { Route as AuthAuthForgetPasswordImport } from './routes/auth/_auth.forget-password'
import { Route as AuthAuthChangePasswordImport } from './routes/auth/_auth.change-password'
import { Route as CategoriesCategoriesSearchIdImport } from './routes/categories/_categories.search.$id'
import { Route as CategoriesCategoryProductProductImport } from './routes/categories/$category.product/_product'
import { Route as AccountAccountTraderIdImport } from './routes/account/_account.trader.$id'

// Create Virtual Routes

const CategoriesImport = createFileRoute('/categories')()
const AuthImport = createFileRoute('/auth')()
const AccountImport = createFileRoute('/account')()
const CategoriesCategoryProductImport = createFileRoute(
  '/categories/$category/product',
)()
const CategoriesCategoriesCategoryLazyImport = createFileRoute(
  '/categories/_categories/$category',
)()
const AuthAuthSignupLazyImport = createFileRoute('/auth/_auth/signup')()
const CategoriesCategoryProductProductProductLazyImport = createFileRoute(
  '/categories/$category/product/_product/$product',
)()

// Create/Update Routes

const CategoriesRoute = CategoriesImport.update({
  path: '/categories',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AccountRoute = AccountImport.update({
  path: '/account',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesCategoriesRoute = CategoriesCategoriesImport.update({
  id: '/_categories',
  getParentRoute: () => CategoriesRoute,
} as any)

const AuthAuthRoute = AuthAuthImport.update({
  id: '/_auth',
  getParentRoute: () => AuthRoute,
} as any)

const AccountAccountRoute = AccountAccountImport.update({
  id: '/_account',
  getParentRoute: () => AccountRoute,
} as any)

const CategoriesCategoryProductRoute = CategoriesCategoryProductImport.update({
  path: '/$category/product',
  getParentRoute: () => CategoriesRoute,
} as any)

const CategoriesCategoriesIndexRoute = CategoriesCategoriesIndexImport.update({
  path: '/',
  getParentRoute: () => CategoriesCategoriesRoute,
} as any)

const AccountAccountIndexRoute = AccountAccountIndexImport.update({
  path: '/',
  getParentRoute: () => AccountAccountRoute,
} as any)

const CategoriesCategoriesCategoryLazyRoute =
  CategoriesCategoriesCategoryLazyImport.update({
    path: '/$category',
    getParentRoute: () => CategoriesCategoriesRoute,
  } as any).lazy(() =>
    import('./routes/categories/_categories.$category.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthAuthSignupLazyRoute = AuthAuthSignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => AuthAuthRoute,
} as any).lazy(() =>
  import('./routes/auth/_auth.signup.lazy').then((d) => d.Route),
)

const AuthAuthVerificationConfirmedRoute =
  AuthAuthVerificationConfirmedImport.update({
    path: '/verification-confirmed',
    getParentRoute: () => AuthAuthRoute,
  } as any)

const AuthAuthVerificationRoute = AuthAuthVerificationImport.update({
  path: '/verification',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthSigninRoute = AuthAuthSigninImport.update({
  path: '/signin',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthForgetPasswordRoute = AuthAuthForgetPasswordImport.update({
  path: '/forget-password',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthChangePasswordRoute = AuthAuthChangePasswordImport.update({
  path: '/change-password',
  getParentRoute: () => AuthAuthRoute,
} as any)

const CategoriesCategoriesSearchIdRoute =
  CategoriesCategoriesSearchIdImport.update({
    path: '/search/$id',
    getParentRoute: () => CategoriesCategoriesRoute,
  } as any)

const CategoriesCategoryProductProductRoute =
  CategoriesCategoryProductProductImport.update({
    id: '/_product',
    getParentRoute: () => CategoriesCategoryProductRoute,
  } as any)

const AccountAccountTraderIdRoute = AccountAccountTraderIdImport.update({
  path: '/trader/$id',
  getParentRoute: () => AccountAccountRoute,
} as any)

const CategoriesCategoryProductProductProductLazyRoute =
  CategoriesCategoryProductProductProductLazyImport.update({
    path: '/$product',
    getParentRoute: () => CategoriesCategoryProductProductRoute,
  } as any).lazy(() =>
    import('./routes/categories/$category.product/_product.$product.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountImport
      parentRoute: typeof rootRoute
    }
    '/account/_account': {
      id: '/account/_account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountAccountImport
      parentRoute: typeof AccountRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/_auth': {
      id: '/auth/_auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthImport
      parentRoute: typeof AuthRoute
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesImport
      parentRoute: typeof rootRoute
    }
    '/categories/_categories': {
      id: '/categories/_categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesCategoriesImport
      parentRoute: typeof CategoriesRoute
    }
    '/auth/_auth/change-password': {
      id: '/auth/_auth/change-password'
      path: '/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof AuthAuthChangePasswordImport
      parentRoute: typeof AuthAuthImport
    }
    '/auth/_auth/forget-password': {
      id: '/auth/_auth/forget-password'
      path: '/forget-password'
      fullPath: '/auth/forget-password'
      preLoaderRoute: typeof AuthAuthForgetPasswordImport
      parentRoute: typeof AuthAuthImport
    }
    '/auth/_auth/signin': {
      id: '/auth/_auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthAuthSigninImport
      parentRoute: typeof AuthAuthImport
    }
    '/auth/_auth/verification': {
      id: '/auth/_auth/verification'
      path: '/verification'
      fullPath: '/auth/verification'
      preLoaderRoute: typeof AuthAuthVerificationImport
      parentRoute: typeof AuthAuthImport
    }
    '/auth/_auth/verification-confirmed': {
      id: '/auth/_auth/verification-confirmed'
      path: '/verification-confirmed'
      fullPath: '/auth/verification-confirmed'
      preLoaderRoute: typeof AuthAuthVerificationConfirmedImport
      parentRoute: typeof AuthAuthImport
    }
    '/auth/_auth/signup': {
      id: '/auth/_auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthAuthSignupLazyImport
      parentRoute: typeof AuthAuthImport
    }
    '/categories/_categories/$category': {
      id: '/categories/_categories/$category'
      path: '/$category'
      fullPath: '/categories/$category'
      preLoaderRoute: typeof CategoriesCategoriesCategoryLazyImport
      parentRoute: typeof CategoriesCategoriesImport
    }
    '/account/_account/': {
      id: '/account/_account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountAccountIndexImport
      parentRoute: typeof AccountAccountImport
    }
    '/categories/_categories/': {
      id: '/categories/_categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesCategoriesIndexImport
      parentRoute: typeof CategoriesCategoriesImport
    }
    '/account/_account/trader/$id': {
      id: '/account/_account/trader/$id'
      path: '/trader/$id'
      fullPath: '/account/trader/$id'
      preLoaderRoute: typeof AccountAccountTraderIdImport
      parentRoute: typeof AccountAccountImport
    }
    '/categories/$category/product': {
      id: '/categories/$category/product'
      path: '/$category/product'
      fullPath: '/categories/$category/product'
      preLoaderRoute: typeof CategoriesCategoryProductImport
      parentRoute: typeof CategoriesImport
    }
    '/categories/$category/product/_product': {
      id: '/categories/$category/product/_product'
      path: '/$category/product'
      fullPath: '/categories/$category/product'
      preLoaderRoute: typeof CategoriesCategoryProductProductImport
      parentRoute: typeof CategoriesCategoryProductRoute
    }
    '/categories/_categories/search/$id': {
      id: '/categories/_categories/search/$id'
      path: '/search/$id'
      fullPath: '/categories/search/$id'
      preLoaderRoute: typeof CategoriesCategoriesSearchIdImport
      parentRoute: typeof CategoriesCategoriesImport
    }
    '/categories/$category/product/_product/$product': {
      id: '/categories/$category/product/_product/$product'
      path: '/$product'
      fullPath: '/categories/$category/product/$product'
      preLoaderRoute: typeof CategoriesCategoryProductProductProductLazyImport
      parentRoute: typeof CategoriesCategoryProductProductImport
    }
  }
}

// Create and export the route tree

interface AccountAccountRouteChildren {
  AccountAccountIndexRoute: typeof AccountAccountIndexRoute
  AccountAccountTraderIdRoute: typeof AccountAccountTraderIdRoute
}

const AccountAccountRouteChildren: AccountAccountRouteChildren = {
  AccountAccountIndexRoute: AccountAccountIndexRoute,
  AccountAccountTraderIdRoute: AccountAccountTraderIdRoute,
}

const AccountAccountRouteWithChildren = AccountAccountRoute._addFileChildren(
  AccountAccountRouteChildren,
)

interface AccountRouteChildren {
  AccountAccountRoute: typeof AccountAccountRouteWithChildren
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAccountRoute: AccountAccountRouteWithChildren,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AuthAuthRouteChildren {
  AuthAuthChangePasswordRoute: typeof AuthAuthChangePasswordRoute
  AuthAuthForgetPasswordRoute: typeof AuthAuthForgetPasswordRoute
  AuthAuthSigninRoute: typeof AuthAuthSigninRoute
  AuthAuthVerificationRoute: typeof AuthAuthVerificationRoute
  AuthAuthVerificationConfirmedRoute: typeof AuthAuthVerificationConfirmedRoute
  AuthAuthSignupLazyRoute: typeof AuthAuthSignupLazyRoute
}

const AuthAuthRouteChildren: AuthAuthRouteChildren = {
  AuthAuthChangePasswordRoute: AuthAuthChangePasswordRoute,
  AuthAuthForgetPasswordRoute: AuthAuthForgetPasswordRoute,
  AuthAuthSigninRoute: AuthAuthSigninRoute,
  AuthAuthVerificationRoute: AuthAuthVerificationRoute,
  AuthAuthVerificationConfirmedRoute: AuthAuthVerificationConfirmedRoute,
  AuthAuthSignupLazyRoute: AuthAuthSignupLazyRoute,
}

const AuthAuthRouteWithChildren = AuthAuthRoute._addFileChildren(
  AuthAuthRouteChildren,
)

interface AuthRouteChildren {
  AuthAuthRoute: typeof AuthAuthRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthRoute: AuthAuthRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CategoriesCategoriesRouteChildren {
  CategoriesCategoriesCategoryLazyRoute: typeof CategoriesCategoriesCategoryLazyRoute
  CategoriesCategoriesIndexRoute: typeof CategoriesCategoriesIndexRoute
  CategoriesCategoriesSearchIdRoute: typeof CategoriesCategoriesSearchIdRoute
}

const CategoriesCategoriesRouteChildren: CategoriesCategoriesRouteChildren = {
  CategoriesCategoriesCategoryLazyRoute: CategoriesCategoriesCategoryLazyRoute,
  CategoriesCategoriesIndexRoute: CategoriesCategoriesIndexRoute,
  CategoriesCategoriesSearchIdRoute: CategoriesCategoriesSearchIdRoute,
}

const CategoriesCategoriesRouteWithChildren =
  CategoriesCategoriesRoute._addFileChildren(CategoriesCategoriesRouteChildren)

interface CategoriesCategoryProductProductRouteChildren {
  CategoriesCategoryProductProductProductLazyRoute: typeof CategoriesCategoryProductProductProductLazyRoute
}

const CategoriesCategoryProductProductRouteChildren: CategoriesCategoryProductProductRouteChildren =
  {
    CategoriesCategoryProductProductProductLazyRoute:
      CategoriesCategoryProductProductProductLazyRoute,
  }

const CategoriesCategoryProductProductRouteWithChildren =
  CategoriesCategoryProductProductRoute._addFileChildren(
    CategoriesCategoryProductProductRouteChildren,
  )

interface CategoriesCategoryProductRouteChildren {
  CategoriesCategoryProductProductRoute: typeof CategoriesCategoryProductProductRouteWithChildren
}

const CategoriesCategoryProductRouteChildren: CategoriesCategoryProductRouteChildren =
  {
    CategoriesCategoryProductProductRoute:
      CategoriesCategoryProductProductRouteWithChildren,
  }

const CategoriesCategoryProductRouteWithChildren =
  CategoriesCategoryProductRoute._addFileChildren(
    CategoriesCategoryProductRouteChildren,
  )

interface CategoriesRouteChildren {
  CategoriesCategoriesRoute: typeof CategoriesCategoriesRouteWithChildren
  CategoriesCategoryProductRoute: typeof CategoriesCategoryProductRouteWithChildren
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesCategoriesRoute: CategoriesCategoriesRouteWithChildren,
  CategoriesCategoryProductRoute: CategoriesCategoryProductRouteWithChildren,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountAccountRouteWithChildren
  '/auth': typeof AuthAuthRouteWithChildren
  '/categories': typeof CategoriesCategoriesRouteWithChildren
  '/auth/change-password': typeof AuthAuthChangePasswordRoute
  '/auth/forget-password': typeof AuthAuthForgetPasswordRoute
  '/auth/signin': typeof AuthAuthSigninRoute
  '/auth/verification': typeof AuthAuthVerificationRoute
  '/auth/verification-confirmed': typeof AuthAuthVerificationConfirmedRoute
  '/auth/signup': typeof AuthAuthSignupLazyRoute
  '/categories/$category': typeof CategoriesCategoriesCategoryLazyRoute
  '/account/': typeof AccountAccountIndexRoute
  '/categories/': typeof CategoriesCategoriesIndexRoute
  '/account/trader/$id': typeof AccountAccountTraderIdRoute
  '/categories/$category/product': typeof CategoriesCategoryProductProductRouteWithChildren
  '/categories/search/$id': typeof CategoriesCategoriesSearchIdRoute
  '/categories/$category/product/$product': typeof CategoriesCategoryProductProductProductLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountAccountIndexRoute
  '/auth': typeof AuthAuthRouteWithChildren
  '/categories': typeof CategoriesCategoriesIndexRoute
  '/auth/change-password': typeof AuthAuthChangePasswordRoute
  '/auth/forget-password': typeof AuthAuthForgetPasswordRoute
  '/auth/signin': typeof AuthAuthSigninRoute
  '/auth/verification': typeof AuthAuthVerificationRoute
  '/auth/verification-confirmed': typeof AuthAuthVerificationConfirmedRoute
  '/auth/signup': typeof AuthAuthSignupLazyRoute
  '/categories/$category': typeof CategoriesCategoriesCategoryLazyRoute
  '/account/trader/$id': typeof AccountAccountTraderIdRoute
  '/categories/$category/product': typeof CategoriesCategoryProductProductRouteWithChildren
  '/categories/search/$id': typeof CategoriesCategoriesSearchIdRoute
  '/categories/$category/product/$product': typeof CategoriesCategoryProductProductProductLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/account/_account': typeof AccountAccountRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/_auth': typeof AuthAuthRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/categories/_categories': typeof CategoriesCategoriesRouteWithChildren
  '/auth/_auth/change-password': typeof AuthAuthChangePasswordRoute
  '/auth/_auth/forget-password': typeof AuthAuthForgetPasswordRoute
  '/auth/_auth/signin': typeof AuthAuthSigninRoute
  '/auth/_auth/verification': typeof AuthAuthVerificationRoute
  '/auth/_auth/verification-confirmed': typeof AuthAuthVerificationConfirmedRoute
  '/auth/_auth/signup': typeof AuthAuthSignupLazyRoute
  '/categories/_categories/$category': typeof CategoriesCategoriesCategoryLazyRoute
  '/account/_account/': typeof AccountAccountIndexRoute
  '/categories/_categories/': typeof CategoriesCategoriesIndexRoute
  '/account/_account/trader/$id': typeof AccountAccountTraderIdRoute
  '/categories/$category/product': typeof CategoriesCategoryProductRouteWithChildren
  '/categories/$category/product/_product': typeof CategoriesCategoryProductProductRouteWithChildren
  '/categories/_categories/search/$id': typeof CategoriesCategoriesSearchIdRoute
  '/categories/$category/product/_product/$product': typeof CategoriesCategoryProductProductProductLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/categories'
    | '/auth/change-password'
    | '/auth/forget-password'
    | '/auth/signin'
    | '/auth/verification'
    | '/auth/verification-confirmed'
    | '/auth/signup'
    | '/categories/$category'
    | '/account/'
    | '/categories/'
    | '/account/trader/$id'
    | '/categories/$category/product'
    | '/categories/search/$id'
    | '/categories/$category/product/$product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/categories'
    | '/auth/change-password'
    | '/auth/forget-password'
    | '/auth/signin'
    | '/auth/verification'
    | '/auth/verification-confirmed'
    | '/auth/signup'
    | '/categories/$category'
    | '/account/trader/$id'
    | '/categories/$category/product'
    | '/categories/search/$id'
    | '/categories/$category/product/$product'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/account/_account'
    | '/auth'
    | '/auth/_auth'
    | '/categories'
    | '/categories/_categories'
    | '/auth/_auth/change-password'
    | '/auth/_auth/forget-password'
    | '/auth/_auth/signin'
    | '/auth/_auth/verification'
    | '/auth/_auth/verification-confirmed'
    | '/auth/_auth/signup'
    | '/categories/_categories/$category'
    | '/account/_account/'
    | '/categories/_categories/'
    | '/account/_account/trader/$id'
    | '/categories/$category/product'
    | '/categories/$category/product/_product'
    | '/categories/_categories/search/$id'
    | '/categories/$category/product/_product/$product'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CategoriesRoute: typeof CategoriesRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CategoriesRoute: CategoriesRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/account",
        "/auth",
        "/categories"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/account": {
      "filePath": "account",
      "children": [
        "/account/_account"
      ]
    },
    "/account/_account": {
      "filePath": "account/_account.tsx",
      "parent": "/account",
      "children": [
        "/account/_account/",
        "/account/_account/trader/$id"
      ]
    },
    "/auth": {
      "filePath": "auth",
      "children": [
        "/auth/_auth"
      ]
    },
    "/auth/_auth": {
      "filePath": "auth/_auth.tsx",
      "parent": "/auth",
      "children": [
        "/auth/_auth/change-password",
        "/auth/_auth/forget-password",
        "/auth/_auth/signin",
        "/auth/_auth/verification",
        "/auth/_auth/verification-confirmed",
        "/auth/_auth/signup"
      ]
    },
    "/categories": {
      "filePath": "categories",
      "children": [
        "/categories/_categories",
        "/categories/$category/product"
      ]
    },
    "/categories/_categories": {
      "filePath": "categories/_categories.tsx",
      "parent": "/categories",
      "children": [
        "/categories/_categories/$category",
        "/categories/_categories/",
        "/categories/_categories/search/$id"
      ]
    },
    "/auth/_auth/change-password": {
      "filePath": "auth/_auth.change-password.tsx",
      "parent": "/auth/_auth"
    },
    "/auth/_auth/forget-password": {
      "filePath": "auth/_auth.forget-password.tsx",
      "parent": "/auth/_auth"
    },
    "/auth/_auth/signin": {
      "filePath": "auth/_auth.signin.tsx",
      "parent": "/auth/_auth"
    },
    "/auth/_auth/verification": {
      "filePath": "auth/_auth.verification.tsx",
      "parent": "/auth/_auth"
    },
    "/auth/_auth/verification-confirmed": {
      "filePath": "auth/_auth.verification-confirmed.tsx",
      "parent": "/auth/_auth"
    },
    "/auth/_auth/signup": {
      "filePath": "auth/_auth.signup.lazy.tsx",
      "parent": "/auth/_auth"
    },
    "/categories/_categories/$category": {
      "filePath": "categories/_categories.$category.lazy.tsx",
      "parent": "/categories/_categories"
    },
    "/account/_account/": {
      "filePath": "account/_account.index.tsx",
      "parent": "/account/_account"
    },
    "/categories/_categories/": {
      "filePath": "categories/_categories.index.tsx",
      "parent": "/categories/_categories"
    },
    "/account/_account/trader/$id": {
      "filePath": "account/_account.trader.$id.tsx",
      "parent": "/account/_account"
    },
    "/categories/$category/product": {
      "filePath": "categories/$category.product",
      "parent": "/categories",
      "children": [
        "/categories/$category/product/_product"
      ]
    },
    "/categories/$category/product/_product": {
      "filePath": "categories/$category.product/_product.tsx",
      "parent": "/categories/$category/product",
      "children": [
        "/categories/$category/product/_product/$product"
      ]
    },
    "/categories/_categories/search/$id": {
      "filePath": "categories/_categories.search.$id.tsx",
      "parent": "/categories/_categories"
    },
    "/categories/$category/product/_product/$product": {
      "filePath": "categories/$category.product/_product.$product.lazy.tsx",
      "parent": "/categories/$category/product/_product"
    }
  }
}
ROUTE_MANIFEST_END */
